# Generated by Django 5.2.1 on 2025-08-17 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phrases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phrase',
            name='is_default',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
