# Generated by Django 5.2.1 on 2025-08-17 18:18

from django.db import migrations

DEFAULTS = {
    "Medication": [
        ("I need pain relief", "Necesito alivio para el dolor"),
        ("Take with food", "Tómelo con comida"),
        ("Do you have allergies?", "¿Tiene alergias?"),
    ],
    "Symptoms": [
        ("I feel dizzy", "Me siento mareado"),
        ("I have a headache", "Tengo dolor de cabeza"),
    ],
}

def seed(apps, schema_editor):
    Category = apps.get_model("categories", "Category")
    Phrase = apps.get_model("phrases", "Phrase")
    for cat_name, pairs in DEFAULTS.items():
        cat, _ = Category.objects.get_or_create(name=cat_name)
        for src, dst in pairs:
            Phrase.objects.get_or_create(
                category=cat,
                text_original=src,
                defaults={
                    "text_translation": dst,
                    "is_default": True,
                    "added_by": None,
                },
            )

def unseed(apps, schema_editor):
    Category = apps.get_model("categories", "Category")
    Phrase = apps.get_model("phrases", "Phrase")
    for cat_name, pairs in DEFAULTS.items():
        try:
            cat = Category.objects.get(name=cat_name)
        except Category.DoesNotExist:
            continue
        Phrase.objects.filter(
            category=cat, is_default=True,
            text_original__in=[src for src, _ in pairs],
        ).delete()

class Migration(migrations.Migration):
    dependencies = [
        ("phrases", "0002_add_is_default_to_phrase"),  # adjust to your exact filename
        ("categories", "0001_initial"),
    ]
    operations = [migrations.RunPython(seed, unseed)]
